
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config.yaml --task_config=configs/imagenet/dmps/sr4_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config.yaml --task_config=configs/imagenet/dmps/sr8_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config.yaml --task_config=configs/imagenet/dmps/inpaint_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config_200.yaml --task_config=configs/imagenet/dmps/inpaint_config_random.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config.yaml --task_config=configs/imagenet/dmps/deblur_gauss_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps/model_config.yaml --diffusion_config=configs/imagenet/dmps/diffusion_config.yaml --task_config=configs/imagenet/dmps/deblur_uniform_config.yaml --save_dir=imagenet_SIAM


python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config.yaml --task_config=configs/imagenet/dmps_ours/sr4_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config.yaml --task_config=configs/imagenet/dmps_ours/sr8_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config.yaml --task_config=configs/imagenet/dmps_ours/inpaint_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config_200.yaml --task_config=configs/imagenet/dmps_ours/inpaint_config_random.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config.yaml --task_config=configs/imagenet/dmps_ours/deblur_gauss_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_ours/model_config.yaml --diffusion_config=configs/imagenet/dmps_ours/diffusion_config.yaml --task_config=configs/imagenet/dmps_ours/deblur_uniform_config.yaml --save_dir=imagenet_SIAM


python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config.yaml --task_config=configs/imagenet/dmps_song/sr4_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config.yaml --task_config=configs/imagenet/dmps_song/sr8_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config.yaml --task_config=configs/imagenet/dmps_song/inpaint_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config_200.yaml --task_config=configs/imagenet/dmps_song/inpaint_config_random.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config.yaml --task_config=configs/imagenet/dmps_song/deblur_gauss_config.yaml --save_dir=imagenet_SIAM
python3 main_Gaussain_batched.py --model_config=configs/imagenet/dmps_song/model_config.yaml --diffusion_config=configs/imagenet/dmps_song/diffusion_config.yaml --task_config=configs/imagenet/dmps_song/deblur_uniform_config.yaml --save_dir=imagenet_SIAM